### ISSUE TITLE
workingDiff inconsistency

### ISSUE THREAD

**Issue by Guria** [lennym/moment-business-time#12]
[readme](https://github.com/lennym/moment-business-time#momentworkingdiff):

> Calculates the difference between two moments, counting only working time. Arguments are as per moment#diff

[moment.js docs](http://momentjs.com/docs/#/displaying/difference/):

> By default, moment#diff will return a number rounded towards zero (down for positive, up for negative). If you want a floating point number, pass true as the third argument.

``` js
// moment#diff
moment('2016-03-18 15:00').diff(moment('2016-03-18 10:30'), 'hour') // 4
moment('2016-03-18 15:00').diff(moment('2016-03-18 10:30'), 'hour', true) // 4.5
moment('2016-03-18 15:00').diff(moment('2016-03-18 14:15'), 'hour') // 0
moment('2016-03-18 15:00').diff(moment('2016-03-18 14:15'), 'hour', true) // 0.75
moment('2016-03-18 15:00').diff(moment('2016-03-18 10:30'), 'day') // 0
moment('2016-03-18 15:00').diff(moment('2016-03-18 10:30'), 'day', true) // 4.5 / 24 = 0.1875
moment('2016-03-18 15:00').diff(moment('2016-03-17 10:30'), 'day') // 1
moment('2016-03-18 15:00').diff(moment('2016-03-17 10:30'), 'day', true) // 1 + (4.5 / 24) = 1.1875
// moment#workingDiff
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 10:30'), 'hour')  // 4 ok
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 10:30'), 'hour', true)  // 4.5 ok
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 14:15'), 'hour') // 0 ok
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 14:15'), 'hour', true) // 0.75 ok
// wtf section
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 10:30'), 'day') // 1 expected to be 0
moment('2016-03-18 15:00').workingDiff(moment('2016-03-18 10:30'), 'day', true) // 1 expected to be 4.5 / 8 = 0.5625
moment('2016-03-18 15:00').workingDiff(moment('2016-03-17 10:30'), 'day') // 2 expected to be 1
moment('2016-03-18 15:00').workingDiff(moment('2016-03-17 10:30'), 'day', true) // 2 expected to be 1 + (4.5 / 8) = 1.5625
```

**Comment by Guria** [comment]
https://tonicdev.com/guria/56ec06044085621200c895f2

**Comment by lennym** [comment]
Thanks @Guria - I strongly suspect this is related to my error in https://github.com/lennym/moment-business-time/issues/8. I'll try to find time to take a look.

**Comment by lennym** [comment]
I'm looking at this now, and the simple case is fixed, but I'm not certain that there's an obvious way to handle the fractional remainders when dealing with days.

In particular, it makes perfect sense in the default case when every working day consists of the same number of hours, but if the locale is amended to make the number of working hours not consistent across days then there's no obvious way to determine the number of hours in a "whole day" in order to perform the division required.

I have gone with an initial approach that when performing `a.workingDiff(b, 'days', true);` then the denominator for the calculation of the fraction part is the number of hours in `b` (or the next working day after `b` if `b` is not a working day).

This does mean that there is the potential for `a.workingDiff(b, 'days', true)` to not correspond to `b.workingDiff(a, 'days', true)` if `a` and `b` have different numbers of hours.

I have added a warning to the code when calling `workingDiff` with a unit of days and full detail.

**Comment by lennym** [comment]
Published at v0.5.0

**Comment by Guria** [comment]
Great, thanks.
BTW, it would be great to wrap warnings with `if (process.env.NODE_ENV !== 'production')` conditional.

**Comment by Guria** [comment]
@lennym I have another [failing test](https://tonicdev.com/guria/56f15266c6e79d1200176630):

``` js
var chai = require('chai');
global.should = chai.should();

var moment = require('moment-business-time');

var END = moment('2016-03-21 17:00')
var START1 = moment('2016-03-18 09:00')
var START2 = moment('2016-03-18 10:00')

END.workingDiff(START1, 'day').should.equal(2)           // expected 1 to be 2
END.workingDiff(START1, 'day', true).should.equal(2)     // ok

END.workingDiff(START2, 'day').should.equal(1)           // ok
END.workingDiff(START2, 'day', true).should.equal(1.875) // ok
```

**Comment by faridnsh** [comment]
It'd be nice to somehow to disable that warning.

**Comment by lennym** [comment]
@alFReD-NSH I'd happily look at a PR if you'd like to open one.
